name: Docker Image CI

on:
  push:
    branches:
      - staging
      - trying

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/docs-eol:${GITHUB_SHA}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: eolito
        password: ${{ secrets.CR_PAT }}

    - name: Push to Github Container Registry
      run: |
        docker push ghcr.io/eol-uchile/docs-eol:${GITHUB_SHA}